#!/usr/bin/env bash
# Install the Chrome/Chromium native-messaging host manifest for com.cookiemonster.gaze.
#
#   ./install_host.sh [--mock] [--extension-id ID] [--uninstall]
#
# Generates bin/cm-gaze-host and bin/cm-gaze-host-mock (absolute paths baked in,
# incl. the uv binary resolved now) and writes com.cookiemonster.gaze.json into:
#   ~/.config/google-chrome/NativeMessagingHosts/
#   ~/.config/chromium/NativeMessagingHosts/
#   ~/snap/chromium/common/chromium/NativeMessagingHosts/   (only if snap chromium exists)
# The extension ID defaults to the contents of ../extension/EXTENSION_ID.
set -euo pipefail

HOST_NAME="com.cookiemonster.gaze"
PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_DIR="$(dirname "$PKG_DIR")"
MOCK=0
UNINSTALL=0
EXT_ID=""

usage() { sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mock) MOCK=1; shift ;;
    --extension-id) EXT_ID="${2:-}"; shift 2 ;;
    --extension-id=*) EXT_ID="${1#*=}"; shift ;;
    --uninstall) UNINSTALL=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

TARGET_DIRS=(
  "$HOME/.config/google-chrome/NativeMessagingHosts"
  "$HOME/.config/chromium/NativeMessagingHosts"
)
if [[ -d "$HOME/snap/chromium" ]]; then
  TARGET_DIRS+=("$HOME/snap/chromium/common/chromium/NativeMessagingHosts")
fi

if [[ $UNINSTALL -eq 1 ]]; then
  for d in "${TARGET_DIRS[@]}"; do
    rm -f "$d/$HOST_NAME.json" && echo "removed $d/$HOST_NAME.json"
  done
  exit 0
fi

if [[ -z "$EXT_ID" && -f "$REPO_DIR/extension/EXTENSION_ID" ]]; then
  EXT_ID="$(tr -d '[:space:]' < "$REPO_DIR/extension/EXTENSION_ID")"
fi
if [[ -z "$EXT_ID" ]]; then
  echo "error: no extension ID (pass --extension-id ID or create extension/EXTENSION_ID)" >&2
  exit 2
fi
if ! [[ "$EXT_ID" =~ ^[a-p]{32}$ ]]; then
  echo "error: '$EXT_ID' does not look like a Chrome extension ID (32 chars a-p)" >&2
  exit 2
fi

UV_BIN="$(command -v uv || true)"
if [[ -z "$UV_BIN" ]]; then
  echo "error: uv not found in PATH" >&2
  exit 2
fi
UV_BIN="$(readlink -f "$UV_BIN")"

write_launcher() {  # $1 = file, $2 = mode
  cat > "$1" <<LAUNCHER
#!/usr/bin/env bash
# Generated by install_host.sh -- Chrome native-messaging launcher ($2 mode).
# Chrome passes the caller origin as an argument; stdout is the protocol channel.
cd "$PKG_DIR" || exit 1
exec "$UV_BIN" run --quiet --frozen --project "$PKG_DIR" python -m gaze_helper $2 "\$@"
LAUNCHER
  chmod 755 "$1"
}

mkdir -p "$PKG_DIR/bin"
write_launcher "$PKG_DIR/bin/cm-gaze-host" native
write_launcher "$PKG_DIR/bin/cm-gaze-host-mock" mock

if [[ $MOCK -eq 1 ]]; then
  HOST_PATH="$PKG_DIR/bin/cm-gaze-host-mock"
  DESC="Cookie Monster gaze helper (MOCK, synthetic gaze)"
else
  HOST_PATH="$PKG_DIR/bin/cm-gaze-host"
  DESC="Cookie Monster gaze helper (local eye tracking)"
fi

MANIFEST="$(cat <<JSON
{
  "name": "$HOST_NAME",
  "description": "$DESC",
  "path": "$HOST_PATH",
  "type": "stdio",
  "allowed_origins": ["chrome-extension://$EXT_ID/"]
}
JSON
)"

for d in "${TARGET_DIRS[@]}"; do
  mkdir -p "$d"
  printf '%s\n' "$MANIFEST" > "$d/$HOST_NAME.json"
  chmod 644 "$d/$HOST_NAME.json"
  echo "wrote $d/$HOST_NAME.json"
done
echo "host: $HOST_PATH"
echo "allowed origin: chrome-extension://$EXT_ID/"
echo "uv: $UV_BIN"
