// Product catalog for the Demo Kitchen Shop. Prices are EUR.

export const SHIPPING = {
  freeThreshold: 50,
  standard: 4.9,
  /** Deliberate UX flaw: only revealed on the checkout page. */
  bulkySurcharge: 14.9,
};

export const categories = [
  {
    slug: "cookware",
    name: "Cookware",
    blurb: "Pans and pasta tools that last a lifetime — the backbone of every home kitchen.",
    accent: "#B5432B",
  },
  {
    slug: "knives",
    name: "Knives & Boards",
    blurb: "Sharp, balanced blades and boards that are kind to their edges.",
    accent: "#2C3540",
  },
  {
    slug: "pantry",
    name: "Pantry",
    blurb: "Small-batch oils and spices we cook with ourselves.",
    accent: "#5B7A23",
  },
  {
    slug: "appliances",
    name: "Appliances",
    blurb: "Countertop workhorses for bakers and coffee lovers.",
    accent: "#A9301F",
  },
];

export const products = [
  {
    id: "pasta-machine",
    sku: "DKS-PM-150",
    name: "Classic Pasta Machine 150",
    category: "cookware",
    price: 69.9,
    compareAt: 84.9,
    rating: 4.7,
    reviewCount: 214,
    badge: "Bestseller",
    stock: "In stock",
    tagline: "Roll silky sheets of fresh pasta in ten thicknesses.",
    description: [
      "The same hand-cranked machine Italian nonnas have used for generations: a chrome-plated steel body, anodised aluminium rollers and a sturdy table clamp that keeps everything steady while you crank.",
      "Ten thickness settings take you from thick pappardelle sheets (setting 0) to see-through ravioli dough (setting 9). The included double cutter makes fettuccine and tagliolini in one pass.",
      "Seen it in a cooking video? This is the machine. Clean with a dry brush — never water — and it will outlive your kitchen.",
    ],
    highlights: ["10 thickness settings (0.6–4.8 mm)", "Fettuccine + tagliolini cutter included", "Chrome-plated steel, made in Italy", "Table clamp up to 4 cm"],
    specs: { Material: "Chrome-plated steel, aluminium rollers", "Roller width": "150 mm", Weight: "2.4 kg", Dimensions: "20 × 18 × 16 cm", Warranty: "10 years", "In the box": "Machine, cutter, clamp, crank" },
    boughtTogether: ["cutting-board", "olive-oil"],
    reviews: [
      { author: "Lena M.", rating: 5, date: "2026-08-14", title: "Fresh tagliatelle in 20 minutes", text: "Watched a carbonara video, bought this the same evening. Clamp holds well on our counter and the dough comes out perfectly even." },
      { author: "Thomas K.", rating: 4, date: "2026-07-02", title: "Great, but read the cleaning notes", text: "Solid machine. Took me a while to find out you must not wash it — wish that was printed on the box." },
      { author: "Giulia R.", rating: 5, date: "2026-05-21", title: "Like my grandmother's", text: "Exactly the model I grew up with. Cheaper here than on the comparison sites when I checked." },
    ],
  },
  {
    id: "chef-knife",
    sku: "DKS-CK-210",
    name: "Damascus Chef's Knife 21 cm",
    category: "knives",
    price: 89.0,
    compareAt: null,
    rating: 4.8,
    reviewCount: 167,
    badge: null,
    stock: "In stock",
    tagline: "67-layer Damascus steel with a razor-sharp VG-10 core.",
    description: [
      "Hand-finished in Seki, Japan, this 21 cm gyuto combines a hard VG-10 core (61 HRC) with 67 layers of softer Damascus steel for a blade that stays sharp and resists chipping.",
      "The full-tang G10 handle is balanced right at the bolster, so long prep sessions don't tire your wrist.",
    ],
    highlights: ["VG-10 core, 61 ± 1 HRC", "67-layer Damascus cladding", "Full tang, G10 handle", "Gift box + edge guard"],
    specs: { "Blade length": "210 mm", Steel: "VG-10 / Damascus", Hardness: "61 HRC", Weight: "198 g", "Edge angle": "15° per side", Warranty: "Lifetime" },
    boughtTogether: ["cutting-board", "cast-iron-pan"],
    reviews: [
      { author: "Markus P.", rating: 5, date: "2026-09-01", title: "Scary sharp", text: "Out of the box it slices tomatoes without any pressure. Beautiful pattern." },
      { author: "Sophie W.", rating: 5, date: "2026-06-11", title: "Worth it", text: "Compared it with three similar knives — this one had the best balance." },
    ],
  },
  {
    id: "cast-iron-pan",
    sku: "DKS-CI-28",
    name: "Pre-seasoned Cast-Iron Skillet 28 cm",
    category: "cookware",
    price: 49.95,
    compareAt: 59.0,
    rating: 4.6,
    reviewCount: 389,
    badge: "-15%",
    stock: "In stock",
    tagline: "Sear, bake and fry — on gas, induction or open fire.",
    description: [
      "A heavy-gauge cast-iron skillet, pre-seasoned with flaxseed oil so it is ready to use on day one. Holds heat like nothing else for perfect sears and crispy guanciale.",
      "Works on every hob including induction, in the oven up to 300 °C and on the barbecue.",
    ],
    highlights: ["Pre-seasoned, ready to cook", "Induction & oven safe", "Two pouring lips", "Helper handle"],
    specs: { Diameter: "28 cm", Depth: "5.5 cm", Weight: "3.1 kg", Hob: "All incl. induction", "Oven safe": "300 °C", Warranty: "Lifetime" },
    boughtTogether: ["olive-oil", "spice-set"],
    reviews: [
      { author: "Jonas B.", rating: 5, date: "2026-08-20", title: "Perfect for guanciale", text: "Rendered the guanciale for my carbonara beautifully. Heavy, but that's the point." },
      { author: "Anna L.", rating: 4, date: "2026-04-03", title: "Good pan", text: "Seasoning was a bit thin, but after a few uses it is great." },
      { author: "Peter H.", rating: 4, date: "2026-02-17", title: "Heavy", text: "Great results but my wife can't lift it with one hand." },
    ],
  },
  {
    id: "olive-oil",
    sku: "DKS-OO-500",
    name: "Cold-pressed Olive Oil, Apulia 500 ml",
    category: "pantry",
    price: 18.5,
    compareAt: null,
    rating: 4.9,
    reviewCount: 96,
    badge: "New harvest",
    stock: "In stock",
    tagline: "Peppery, grassy extra virgin oil from a single estate.",
    description: [
      "Pressed within six hours of harvest from Coratina olives on a small family estate near Bari. Bright, grassy and pleasantly peppery — made for finishing pasta, salads and bread.",
    ],
    highlights: ["Extra virgin, single estate", "Harvest 2025/26", "Dark glass bottle", "Acidity < 0.3 %"],
    specs: { Volume: "500 ml", Origin: "Apulia, Italy", Cultivar: "Coratina", Acidity: "< 0.3 %", "Best before": "12/2027" },
    boughtTogether: ["pasta-machine", "spice-set"],
    reviews: [
      { author: "Clara S.", rating: 5, date: "2026-09-12", title: "Tastes like Italy", text: "Peppery finish, beautiful on fresh pasta with a little parmesan." },
      { author: "David F.", rating: 5, date: "2026-07-30", title: "Re-ordered three times", text: "Best oil I've had at this price." },
    ],
  },
  {
    id: "stand-mixer",
    sku: "DKS-SM-1000",
    name: "Stand Mixer Artisan 4.8 L",
    category: "appliances",
    price: 349.0,
    compareAt: 429.0,
    rating: 4.5,
    reviewCount: 142,
    badge: "Sale",
    stock: "Only 3 left",
    tagline: "1000 W planetary mixer with dough hook, whisk and beater.",
    description: [
      "A die-cast metal stand mixer with a 1000 W motor and planetary mixing action that reaches every corner of the 4.8 L stainless-steel bowl.",
      "Ten speeds, a tilt-head design and the optional pasta-roller attachment make it the centrepiece of a baker's kitchen.",
    ],
    highlights: ["1000 W, 10 speeds", "4.8 L stainless-steel bowl", "Dough hook, whisk, flat beater", "Attachment hub for pasta rollers"],
    specs: { Power: "1000 W", Bowl: "4.8 L stainless steel", Speeds: "10", Weight: "10.8 kg", Colour: "Tomato red", Warranty: "5 years" },
    boughtTogether: ["pasta-machine", "spice-set"],
    reviews: [
      { author: "Miriam T.", rating: 5, date: "2026-06-25", title: "Bread every weekend now", text: "Kneads heavy dough without wobbling." },
      { author: "Florian G.", rating: 4, date: "2026-03-14", title: "Loud on high speed", text: "Very capable, but loud at speed 8+." },
      { author: "Eva N.", rating: 4, date: "2026-01-09", title: "Pricey but good", text: "Found it for less elsewhere once, but the warranty here is longer." },
    ],
  },
  {
    id: "espresso-machine",
    sku: "DKS-EM-58",
    name: "Dual-Boiler Espresso Machine Pro",
    category: "appliances",
    price: 499.0,
    compareAt: 579.0,
    rating: 4.4,
    reviewCount: 78,
    badge: null,
    stock: "In stock",
    tagline: "Café-quality espresso with PID temperature control.",
    // Deliberate flaw: bulky-item surcharge only revealed at checkout.
    bulky: true,
    description: [
      "Two independent boilers let you pull a shot and steam milk at the same time. PID control keeps brew water within ±1 °C, and the commercial 58 mm portafilter fits every café accessory.",
      "Pre-infusion, a built-in pressure gauge and a hot-water tap round off a machine that grows with your barista skills.",
    ],
    highlights: ["Dual boiler, PID ±1 °C", "58 mm commercial portafilter", "Pre-infusion + pressure gauge", "2.5 L water tank"],
    specs: { Pump: "15 bar vibration pump", Boilers: "0.3 L brew / 0.95 L steam", Power: "1800 W", Weight: "16 kg", Dimensions: "37 × 33 × 39 cm", Warranty: "3 years" },
    boughtTogether: ["cutting-board", "spice-set"],
    reviews: [
      { author: "Stefan R.", rating: 5, date: "2026-08-05", title: "Finally proper flat whites", text: "Steams milk while brewing — game changer." },
      { author: "Laura K.", rating: 3, date: "2026-05-18", title: "Surprise shipping fee", text: "Great machine, but I only saw the €14.90 freight surcharge at the very end of checkout. Almost cancelled." },
      { author: "Nico A.", rating: 4, date: "2026-02-22", title: "Heavy beast", text: "Excellent espresso, needs a lot of counter space." },
    ],
  },
  {
    id: "cutting-board",
    sku: "DKS-CB-45",
    name: "End-grain Walnut Cutting Board",
    category: "knives",
    price: 39.9,
    compareAt: null,
    rating: 4.7,
    reviewCount: 121,
    badge: null,
    stock: "In stock",
    tagline: "Self-healing end grain that keeps your knives sharp.",
    description: [
      "Made from solid American black walnut, end-grain construction lets knife edges slip between the fibres instead of cutting across them — gentler on your blades, and the surface closes up again.",
    ],
    highlights: ["Solid black walnut, end grain", "Juice groove on reverse", "Non-slip feet", "Oiled with food-safe mineral oil"],
    specs: { Size: "45 × 30 × 4 cm", Wood: "American black walnut", Weight: "3.4 kg", Care: "Hand wash, oil monthly" },
    boughtTogether: ["chef-knife", "olive-oil"],
    reviews: [
      { author: "Hannah J.", rating: 5, date: "2026-07-14", title: "Gorgeous", text: "Looks like furniture. Knife feels great on it." },
      { author: "Tobias E.", rating: 4, date: "2026-03-28", title: "Heavy and solid", text: "Doesn't move at all while chopping." },
    ],
  },
  {
    id: "spice-set",
    sku: "DKS-SP-04",
    name: "Italian Kitchen Spice Set (4 jars)",
    category: "pantry",
    price: 29.9,
    compareAt: 34.9,
    rating: 4.3,
    reviewCount: 58,
    badge: null,
    stock: "In stock",
    tagline: "Smoked paprika, turmeric, oregano and Tellicherry pepper.",
    description: [
      "Four refillable glass jars with our favourite everyday spices, freshly ground in small batches: smoked paprika, turmeric, Sicilian oregano and coarse Tellicherry black pepper — essential for cacio e pepe and carbonara.",
    ],
    highlights: ["4 × 60 g glass jars", "Small-batch ground", "Wooden wall rack included", "Refill pouches available"],
    specs: { Contents: "4 × 60 g", Jars: "Glass, bamboo lids", Rack: "Oak, wall-mountable", Origin: "Various, packed in Austria" },
    boughtTogether: ["olive-oil", "cast-iron-pan"],
    reviews: [
      { author: "Julia Z.", rating: 4, date: "2026-08-29", title: "Lovely pepper", text: "The Tellicherry pepper is outstanding in cacio e pepe." },
      { author: "Martin O.", rating: 4, date: "2026-04-11", title: "Nice gift", text: "Bought as a gift, well packaged." },
    ],
  },
];

export const productById = Object.fromEntries(products.map((p) => [p.id, p]));

const eur = new Intl.NumberFormat("de-AT", { style: "currency", currency: "EUR" });
export const formatPrice = (n) => eur.format(n);
